23
GDKsoftware/GitBitter pull request #31
Opened 2017-02-18 21:42 UTC by partouf

2017-02-18 23:07 UTC, martinvd requested changes

2017-02-18 23:07 UTC, martinvd commented on GitBitterLib/Implementations/GitSharpCloner.cs
> +                return (_url, _user, _cred) => credentials;
Both returns are same and can be placed below if-statement. Same for `credentials.Username = "git";`.

2017-02-18 23:08 UTC, martinvd commented
"martinvd requested changes just now" lol :smile:

2017-02-18 23:11 UTC, partouf commented on GitBitterLib/Implementations/GitSharpCloner.cs
> +                return (_url, _user, _cred) => credentials;
yes, need to figure out what the base class is of both credential objects though.. but, will do

2017-02-19 01:07 UTC, partouf commented
Base class doesn't have all the properties, so it would be a mess of typecasting vs what it is now

2017-02-19 01:07 UTC, merged